### ISSUE TITLE
Новий функціонал - керування пінгами

### ISSUE THREAD

**Issue by roma7080** [Baskerville42/svitloboard#1]
В якості пропозиції на сторінці введення ключа каналу додати:
1. Чекбокс "Посилати запити" (за замовчуванням активовано) при деактивації перестає виконувати запити до API
2. Дропдаун з кастомними варіантами інтервалу між запитами. Варіанти інтервалів: 1, 2, 3, 4, 5 хвилин. За замовчуванням -1 хвилина.
3. Текстовий рядок з датою/часом останнього звернення до API та відповіддю сервера.

**Comment by Baskerville42** [comment]
> В якості пропозиції на сторінці введення ключа каналу додати:
> 
> 1. Чекбокс "Посилати запити" (за замовчуванням активовано) при деактивації перестає виконувати запити до API
> 2. Дропдаун з кастомними варіантами інтервалу між запитами. Варіанти інтервалів: 1, 2, 3, 4, 5 хвилин. За замовчуванням -1 хвилина.
> 3. Текстовий рядок з датою/часом останнього звернення до API та відповіддю сервера.

Вітаю!

Дякую за пропозицію.

1. Чекбокс я внесу в список [TODO](https://github.com/Baskerville42/svitloboard#todo) — це чудова ідея!
2. Тут я попрошу пояснити користь від такої опції. На сервері СвітлоБота встановлено інтервал у 5 хвилин для того, щоб при зникненні зв'язку був час переключитися на іншу мережу. У ESP контролера немає RTC, і взагалі, відчуття часу у нього, ну, таке собі. Припустимо ситуацію, коли розсинхронізація часу складе більше однієї секунди, вибраний параметр 5 хвилин, плюс час на виконання запиту — ми отримуємо хибне спрацювання на рівному місці. 
3. За цю функцію я не впевнений, що вона принесе практичну користь.
Чесно кажучи, для цього я робив сторінку статусу. Поясню проблему: для того щоб знати час/дату останнього запиту, потрібно кудись записати значення (в EEPROM). EEPROM пам'ять — вона не як флешка, на яку можна записувати дані в необмеженій кількості. Рано чи пізно область пам'яті деградує від регулярного запису, і почнуться проблеми в роботі контролера.

**Comment by roma7080** [comment]
2. Ідея була в тому щоб використовувати більше девайсів з більшим інтервалом на кодному. Аде дійсно втрачаїться сенс якщо враховувати особливості роботи з часом......
3. Суть в тому щоб розуміти чи вдало пройшло звернення до API. Статус може бути ОК якщо одночасно налаштовано пінг зовнішього АПІ і пінг був успішний. Писати результат запиту в пям'ять точно було б неправильно.
 В будь-якому випадку все це не критично.

**Comment by Baskerville42** [comment]
> 2. Ідея була в тому щоб використовувати більше девайсів з більшим інтервалом на кодному. Аде дійсно втрачаїться сенс якщо враховувати особливості роботи з часом......
> 3. Суть в тому щоб розуміти чи вдало пройшло звернення до API. Статус може бути ОК якщо одночасно налаштовано пінг зовнішього АПІ і пінг був успішний. Писати результат запиту в пям'ять точно було б неправильно.
>    В будь-якому випадку все це не критично.

Тоді я думаю, що для роботи двох і більше пристроїв одночасно потрібно не таймаут налаштовувати, а такий собі delay. Тобто пристрій А стартує разом з пристроєм Б відразу при увімкненні світла, але пристрій Б надсилає запити кожні 1 хвилину + (15/30/45/) секунд. Відтермінування в секундах для прикладу. Тоді у нас не буде одночасних запитів, і нас не блокуватимуть. Сподіваюсь, я правильно зрозумів суть питання?

Щодо статусу — пропоную поки залишити питання відкритим. Вже є сторінка Статусу, є Статус у телеграм-боті. Робити якісь маніпуляції на UI я поки не бачу доцільним. Якщо бажаєте — зробіть pull request зі своїми змінами, я подивлюсь, як це має працювати вживу, і, можливо, додам до прошивки.

**Comment by roma7080** [comment]
> 
> Тоді я думаю, що для роботи двох і більше пристроїв одночасно потрібно не таймаут налаштовувати, а такий собі delay. Тобто пристрій А стартує разом з пристроєм Б відразу при увімкненні світла, але пристрій Б надсилає запити кожні 1 хвилину + (15/30/45/) секунд. Відтермінування в секундах для прикладу. Тоді у нас не буде одночасних запитів, і нас не блокуватимуть. Сподіваюсь, я правильно зрозумів суть питання?
> 
> Щодо статусу — пропоную поки залишити питання відкритим. Вже є сторінка Статусу, є Статус у телеграм-боті. Робити якісь маніпуляції на UI я поки не бачу доцільним. Якщо бажаєте — зробіть pull request зі своїми змінами, я подивлюсь, як це має працювати вживу, і, можливо, додам до прошивки.

Виглядає як недоцільне ускладнення... Думаю варто обмежитись чекбоксом і закрити.

**Comment by Baskerville42** [comment]
[Додав](https://github.com/Baskerville42/svitloboard/commit/2ee59e5c2a253d3fae7b7a13862e89b32deeda61) в список TODO побажання ставити запити до API на паузу.
Тікет закриваю.
