### ISSUE TITLE
Варіант вирішення проблеми з не порожнім EEPROM

### ISSUE THREAD

**Issue by roma7080** [Baskerville42/svitloboard#2]
В рязі коли EEPROM не порожній.
Як працює зараз:
плата завантажується, бачить записи в EEPROM, пробує підключитись до WiFi, не може підключитись і на тому зупиняється.
В такому разі налаштування змінити немає можливості.

Пропонована послідовність роботи:
Після кількох невдали спроб підключитись до WiFi плата переходить в режим точки доступу на 2 хвилини. За цей час користувач має змогу підключитись і змінити налаштування в EEPROM. В тому числі якщо наприклад зберіг неправильні налаштування.
Якщо нема підключень до інтерфейсу протягом 2 хвилин - плата знову починає працювати в режимі клієнта і пробувати підключитись до WiFi.

**Comment by Baskerville42** [comment]
Вітаю!

Я зараз вивчаю питання, як це краще реалізувати, щоб було зручно кінцевому користувачеві.

Поки що в [Known Issues](https://github.com/Baskerville42/svitloboard#known-issues) є робочий workaround — скинути контролер одразу після прошивки чотирма послідовними вимкненнями/увімкненнями. Поки що це найкращий варіант, бо я не хочу ускладнювати логіку основного функціоналу, а саме, переключення контролера на резервні мережі в разі відсутності або помилкового введення даних основної WiFi мережі. Пропоную поки це питання лишити відкритим, можливо, хтось запропонує кращий варіант.

**Comment by roma7080** [comment]
Нажаль варіант 4 ребути у мене не спрацював..... Логи з COM порта не збереглись......
Довелось залити скетч який тупо записав циклом 512К нулів.

**Comment by Baskerville42** [comment]
> Нажаль варіант 4 ребути у мене не спрацював..... Логи з COM порта не збереглись...... Довелось залити скетч який тупо записав циклом 512К нулів.

Тут можна зробити прапорець, який має бути true за замовчуванням. Ідея така: якщо це перший старт прошивки і є якісь (навіть помилкові) дані в памʼяті, ми відразу їх витираємо, бо в цього прапорця значення завжди буде true. Якщо прапорець буде false, то нічого робити не потрібно.

**Comment by roma7080** [comment]
> > Нажаль варіант 4 ребути у мене не спрацював..... Логи з COM порта не збереглись...... Довелось залити скетч який тупо записав циклом 512К нулів.
> 
> Тут можна зробити прапорець, який має бути true за замовчуванням. Ідея така: якщо це перший старт прошивки і є якісь (навіть помилкові) дані в памʼяті, ми відразу їх витираємо, бо в цього прапорця значення завжди буде true. Якщо прапорець буде false, то нічого робити не потрібно.

Логічно - але не рятує у випадку якщо користувач ввів непраильні параметри мережі або параметри мережі змінились. Хоча тут має врятувати варіант 4 ресети. Постараюсь всеж більш прискіпливо протестувати останній......

**Comment by Baskerville42** [comment]
> > > Нажаль варіант 4 ребути у мене не спрацював..... Логи з COM порта не збереглись...... Довелось залити скетч який тупо записав циклом 512К нулів.
> > 
> > 
> > Тут можна зробити прапорець, який має бути true за замовчуванням. Ідея така: якщо це перший старт прошивки і є якісь (навіть помилкові) дані в памʼяті, ми відразу їх витираємо, бо в цього прапорця значення завжди буде true. Якщо прапорець буде false, то нічого робити не потрібно.
> 
> Логічно - але не рятує у випадку якщо користувач ввів непраильні параметри мережі або параметри мережі змінились. Хоча тут має врятувати варіант 4 ресети. Постараюсь всеж більш прискіпливо протестувати останній......

Можливо, у мене не точність в інструкціях. Для скидання потрібно вимкнути-ввімкнути-вимкнути-ввімкнути-вимкнути-ввімкнути-вимкнути-ввімкнути і лишити увімкненим на декілька секунд. В цей момент в моніторі порта значення Boot count має стати 4, і відразу відбудеться перезавантаження. Перезавантаження означатиме, що пристрій очистив памʼять. Якщо не вийде, можемо в телеграмі списатися і дослідити проблему вживу.

**Comment by roma7080** [comment]
> 
> Можливо, у мене не точність в інструкціях. Для скидання потрібно вимкнути-ввімкнути-вимкнути-ввімкнути-вимкнути-ввімкнути-вимкнути-ввімкнути і лишити увімкненим на декілька секунд. В цей момент в моніторі порта значення Boot count має стати 4, і відразу відбудеться перезавантаження. Перезавантаження означатиме, що пристрій очистив памʼять. Якщо не вийде, можемо в телеграмі списатися і дослідити проблему вживу.

Дякую. Треба просто трохи розгребтись щоб знайти вільну платку - десь мала ще валятись :)

**Comment by roma7080** [comment]
> 
> Можливо, у мене не точність в інструкціях. Для скидання потрібно вимкнути-ввімкнути-вимкнути-ввімкнути-вимкнути-ввімкнути-вимкнути-ввімкнути і лишити увімкненим на декілька секунд. В цей момент в моніторі порта значення Boot count має стати 4, і відразу відбудеться перезавантаження. Перезавантаження означатиме, що пристрій очистив памʼять. Якщо не вийде, можемо в телеграмі списатися і дослідити проблему вживу.

Протестував функцію скидання - все працює. Дякуючи більш детальній інструкції зміг відслідкувати в чому була моя проблема. Виявилось що я виключав-включав занадто швидко - завантаження просто не доходило до етапу на якому Boot count збільшувався.
Дослідним шляхом виявив що час між вмиканням-вимиканням має бути не меншим за 2 секунди. Можливо, варто додати це в інстукцію.
![Boot4](https://github.com/user-attachments/assets/e1d8b3f5-88f8-4ccf-9cfe-cf65b0467cc4)

В такому випадку виглядає що реалізація функціє очищення пам'яті при першому завантаженні + уточнення інструкції цілком врішує всі проблеми. Можна кейс закривати.

**Comment by Baskerville42** [comment]
[Оновив](https://github.com/Baskerville42/svitloboard/commit/e3e763fc175ef3073744485f63a5abf91375ee2a) розділ Known issues і додав інструкцію з діаграмою.
Тікет закриваю.
